### ISSUE TITLE
Maintain a change log for future releases

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/modelator#101]
Modelator is going through many breaking changes.

It would be nice if we track these changes through important PRs using [unclog](https://github.com/informalsystems/unclog).

- [x] Setup `unclog`  
- [x] Prepare a [PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests)
- [x] Write a `CONTRIBUTING.md`
- [x] Initialize `CHANGELOG.md` with a summary of past changes

**Comment by danwt** [comment]
Reassigning to @rnbguy per our discussion last week.

**Comment by rnbguy** [comment]
Closed by #129 (52d188c)
