### ISSUE TITLE
A protocol and a prototype for MBT-core <-> MBT-Rust communication

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#11]
Following the description outlined in https://github.com/informalsystems/modelator/issues/2#issuecomment-785870955., we need to split the jobs of generating and executing tests into MBT-core and MBT-Rust plugin. For that we need to devise a simple protocol for the communication of MBT-core and MBT-Rust, and do a prototype implementation of it. 

As a testing ground for the protocol, it is proposed to take the work done in [IBC-rs#701](https://github.com/informalsystems/ibc-rs/pull/701), and to separate it into MBT-Core and MBT-Rust:
- MBT-core will have the task of running TLC on the provided spec, and generating tests from it. It will run as a daemon listening for local requests.
- MBT-Rust will run the given test executor implementation on the tests obtained via communication with MBT-core.

In the first iteration we should not care too much about the particularities of the implementation, but to focus on obtaining a minimal working prototype that has MBT-core and MBT-Rust separated and communicating via a protocol. This will be refactored later for a better code structure.

**Comment by danwt** [comment]
Closed as outdated. Please reopen if this is a mistake.
