### ISSUE TITLE
[BUG] User experience: if no trace is found for a test then it should be considered a failure from the point of view of the user.

### ISSUE THREAD

**Issue by danwt** [informalsystems/modelator#113]
## Description

The definition of failure differs when looking from the model checking point of view and the model-based testing point of view. From the model checking point of view, your model/system has an error if a trace is found that violates an invariant. From the MBT point of view your model/system has a failure if you write a _Test_ (invariant) for which no trace is found. The two points of view should be reflected clearly.

## Expected behavior

When a Test has been written for which no trace can be found then it should be reported as an error to the user.

**Comment by andrey-kuprianov** [comment]
@rnbguy could you please take care of this issue before 0.4.0 release? Thanks!

**Comment by rnbguy** [comment]
This is already handled by producing `NoTestTraceFound` error.

https://github.com/informalsystems/modelator/blob/f26f7439b2f3b70a89fd48666370e6a0f0ff4cc3/rs/modelator/src/model/checker/apalache/mod.rs#L93-L98

https://github.com/informalsystems/modelator/blob/f26f7439b2f3b70a89fd48666370e6a0f0ff4cc3/rs/modelator/src/model/checker/tlc/mod.rs#L79-L84
