### ISSUE TITLE
Upgrade to Apalache v0.17.5

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#119]
There is a substantial upgrade from the Apalache side: we have v. 0.15.3 currently; but version 0.17.1 has been released; we should upgrade as well.

**Comment by rnbguy** [comment]
Also, it would be nice to rely on Apalache's release packages to download the jar file, instead of pulling it from our repository.

**Comment by shonfeder** [comment]
I'm guessing https://github.com/informalsystems/apalache/issues/1077 is a bit of a blocker for the upgrade? I should have that fixed by tomorrow, and we can cut a new release in the afternoon.

**Comment by andrey-kuprianov** [comment]
@shonfeder right, informalsystems/apalache#1077 is standing in the way a bit. I was going to still adopt the current output scheme in 0.17.1, but definitely can wait another day, if that's not too much of a headache for you to address it:)

**Comment by shonfeder** [comment]
I'm optimistic I'll be able to get a fix in by OED tomorrow!

**Comment by shonfeder** [comment]
The changes ended up being more involved than I'd anticipated. But, assuming Igor or Jure approve, I think it's ready in https://github.com/informalsystems/apalache/pull/1081.

I'm off next week, but hopefully Jure or Igor can make any fixes they see fit to help the PR along.

**Comment by danwt** [comment]
If this is urgent-ish then I suggest making the changes inside this (the modelator) repo as needed. For next time, I suggest we move all Apalache/TLC versioning issues and downloads to the [mbt-python](github.com/informalsystems/mbt-python/) repo and use only the pure interfaces available from mbt-python inside this repo.
