### ISSUE TITLE
MBT-core: TLA+ history can be prohibitively heavy

### ISSUE THREAD

**Issue by vitorenesduarte** [informalsystems/modelator#13]
Related: #4 

After adding a `history` variable to my model, TLC doesn't finish because my machine runs out of disk space.
I worked around it by simply having a `previousState` variable.

I believe such variable will suffice for most use-cases (I checked and this is the case in most of the light client tests (e.g. https://github.com/informalsystems/tendermint-rs/blob/master/light-client/tests/support/model_based/LightTests.tla#L182-L187)) and should be sufficiently lightweight to not affect model checking performance/termination.

**Comment by danwt** [comment]
Just throwing this in here: TLC lets you use a VIEW operator to define a projection from the state defined by the set of all variables to some arbitrary function thereof. A simple use given variables `hist`, `x` would be to declare `View == x`. That way you can still use `hist` for output (by dumping JSON I think) but TLC will no longer differentiate two states `<<hist1,x1>>` from `<<hist2,x2>>` with `x1=x2` and `hist1#hist2`.

I am not familiar with TLC!Trace which may well be a better solution.

**Comment by danwt** [comment]
Closing as this doesn't seem to be presenting an issue or task.
