### ISSUE TITLE
[BUG] Modelator fails on some specs

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#130]
The latest Modelator from main fails on [this spec](https://github.com/informalsystems/modelator/blob/andrey/interchain-accounts/rs/modelator/tests/integration/resource/ICA_0.tla) both with Apalache and with TLC:

```
modelator trace ICA_0.tla ICA_0.cfg
{
  "status": "success",
  "result": {
    "TestRegisterInterchainAccountFailure": {
      "Err": {
        "Nom": "Parsing Failure: Error { input: \"\\\\in {} |-> x ]\\n\\n\", code: Tag }"
      }
    },
    "TestRegisterInterchainAccountSuccess": {
      "Err": {
        "Nom": "Parsing Failure: Error { input: \"\\\\in {} |-> x ]\\n\\n\", code: Tag }"
      }
    }
  }
}
```

```
modelator trace -m tlc ICA_0.tla ICA_0.cfg
thread 'main' panicked at '[modelator] full TLA state should have been parsed', modelator/src/model/language/tla/json/mod.rs:10:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@rnbguy could you please take a look?

**Comment by rnbguy** [comment]
The error is from [`parse_state`](https://github.com/informalsystems/modelator/blob/deb5c9ad6518624780274ce1f2692374d36438df/rs/modelator/src/model/language/tla/json/parser.rs#L13) function. The input was
```
action = [type |-> ""] /\ outcome = FALSE /\ ports = [ x \in {} |-> x ]
```

**Comment by andrey-kuprianov** [comment]
As it turned out, addressing this issue requires non-trivial changes to the parser, which trigger changes in the JSON representation down-stream. It's not worth it.

We will do the following:
