### ISSUE TITLE
[FEATURE] Support Invariant predicates along with Test predicates

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/modelator#141]
Right now, Modelator takes a _Test Predicate_, which means Modelator produces a trace that satisfies the predicate.

If a user wants to check an _Invariant_, the current Modelator workflow allows testing  _~Invariant_, that is, to produce a trace that satisfies the negation of the invariant. But this may introduce confusion to a new user.

Also, model checkers produce counter-examples to an _Invariant Predicate_, which means model checkers generate a trace that violates the predicate. So this may introduce confusion even to the users familiar with the model checkers.

To remove this confusion of negation, it would be convenient if Modelator takes both `Test` and `Invariant` predicates and process them accordingly.

**Comment by danwt** [comment]
I don't understand the feature. If the model is correct the invariant will never be violated so no trace will be generated and there will be nothing to test?
