### ISSUE TITLE
[BUG] fails with `modelator trace --model-checker tlc spec.tla spec.cfg`

### ISSUE THREAD

**Issue by danwt** [informalsystems/modelator#156]
_modelator 0.4.1_

## Description

```bash
modelator trace --model-checker tlc spec.tla spec.cfg
thread 'main' panicked at '[modelator] full TLA state should have been parsed', modelator/src/model/language/tla/json/mod.rs:10:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I need time to create a minimal example.

## System information

- OS: OSX Big Sur M1

## Additional context

Mirrors https://github.com/informalsystems/mbt/issues/45

**Comment by rnbguy** [comment]
The parser throws error because it does not support ranged sets i.e. `1..10`. Let me create a PR to add support.
