### ISSUE TITLE
Explore with how an interactive shell could be used with Modelator

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/modelator#177]
The idea is to give a simple environment to experiment with modelator. A common place from which different options can be set and tested per specification. 

At the moment, this means:
 - loading a model file
 - reporting parsing/typechecking errors on it
 - setting different parameters (which typechecker to use, how many counterexamples to correct etc., running in parallel both TLC and Apalache)
 - scripting support (to enable users of the shell to combine different parts in any way they see fit)

For this issue, just the exploration of how to implement basic commands and give them inside an interactive shell is needed

**Comment by danwt** [comment]
I hinted at this in a chat with @andrey-kuprianov but I would personally be more excited to see not a raw shell but rather some kind of scripting support (Jupyter notebooks come to mind).
