### ISSUE TITLE
High level Modelator commands

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/modelator#178]
Implement the basic, high-level feature requests (amounts to calls to corresponding Apalache/TLC commands, wrapped by [modelator-py](https://github.com/informalsystems/modelator-py).
Subtasks:
 

- [x] Parse: [PR](https://github.com/informalsystems/modelator/pull/175)
- [x] Typecheck
- [ ] Check
- [ ] Show
- [ ] Trace
- [ ] Execute
- [ ] Test

**Comment by rnbguy** [comment]
You can still use this issue as a global tracker of Modelator shell. But you can remove it from the board.
