### ISSUE TITLE
`python -i` introduces packaging and setup overhead

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/modelator#196]
In my opinion `python -i modelator_shell.py` is not a good idea for packaging, because we have to maintain it and a user has to download the py-file explicitly.

We should go for `from modelator.shell import *` directly from the python module. A user needs to execute `pip install modelator` to install the main `modelator` module, anyway.

Currently, we have to maintain `modelator_shell.py` separately and a user has to do the following,
```sh
pip install modelator
curl -O https://path/to/modelator_shell.py
python -i modelator_shell.py
>>>
```
Not to forget, if the user changes the working directory, she has to move the `modelator_shell.py`.

I am proposing the following without maintaining a separate `modelator_shell.py`,
```sh
pip install modelator
python
>>> from modelator.shell import *
>>>
```

Also, we can not use `python -i modelator_shell.py` in Jupyter notebook. We have to import it as `from modelator_shell import *` after downloading the py-file. But, we can reuse the importing-from-module setup inside Jupyter notebook.

**Comment by andrey-kuprianov** [comment]
@rnbguy I have already started to write the [high-level user documentation](https://github.com/informalsystems/modelator/blob/andrey/api_shell_doc/Modelator.md) along the lines you also outline above; I hope you'll like it:)
