### ISSUE TITLE
Implement Shell Monitor

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#203]
As outline in the [(WIP) Modelator API](https://github.com/informalsystems/modelator/blob/main/modelator.py), we will have model monitors (following the observer pattern) that will display actions done on the model in various ways.

The task of a ShellMonitor is to overlay in the terminal (in Python shell) model status information, such as parsing status, valid/failed invariants, successful/unsuccessful examples, etc.

**Comment by ivan-gavran** [comment]
@andrey-kuprianov , shall we close this issue, or move to no status? (we will do it once, but it is not in the short-term plan now)
