### ISSUE TITLE
adding poetry dependency is unsuccessful

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/modelator#208]
When I try to add poetry dependency, it throws an error.

```
$ poetry add git+ssh://git@github.com:informalsystems/modelator
...
ValueError: Both /home/user/.cache/pypoetry/virtualenvs/mbt-demo-XXX-py3.10/src/modelator/modelator and /home/user/.cache/pypoetry/virtualenvs/mbt-demo-XXX-py3.10/src/modelator/modelator.py exist
```

The issue is having [`modelator.py`](https://github.com/informalsystems/modelator/blob/main/modelator.py) at the project root.

Having both `modelator/__init__.py`  and `modelator.py` creates a conflict. The `python` will pickup `modelator/__init__.py`, but poetry throws an error explicitly - which is nice IMO.

Can we move this to somewhere else @andrey-kuprianov ?

**Comment by andrey-kuprianov** [comment]
oh yes! please just rename it somehow
