### ISSUE TITLE
Handle jar files properly

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/modelator#212]
As uncovered in Issue #209, modelator does not handle storing `jar` files properly.

One suggested option was to use [appdirs](https://github.com/ActiveState/appdirs) to store files.

Another suggestion was to auto-fetch releases: we should be careful about that, as we know that TLC can change a release without giving it a separate name (and thus we lose control over what's there in Modelator).

**Comment by shonfeder** [comment]
I think it might be worth filing (or updating) an issue on the tlatools repo explaining why their unstable release process is so problematic. It probably won't fix our short-term needs, but should it could help fix this for us down the line and it will put beneficial pressure towards more sustainable behavior on this key feature of the TLA ecosystem.

**Comment by rnbguy** [comment]
TLC has a stable release from February 2022. We can work with that.

@andrey-kuprianov @hvanz @ivan-gavran what do you think?

**Comment by ivan-gavran** [comment]
Aha, good to know! (Didn't know that that changed). Yes, in that case, I agree that pulling a release is a good idea.

**Comment by rnbguy** [comment]
Nothing changed. They just did a stable release in February. They still do their unstable releases by overwriting previous unstable releases.

**Comment by ivan-gavran** [comment]
OK, now I understand: the one for February is guaranteed to be stable, but the still have an unstable release that keeps being overwritten. 

I think it makes sense to proceed by downloading releases as dependencies and not storing them in our repo.
