### ISSUE TITLE
Add CLI integration tests

### ISSUE THREAD

**Issue by hvanz** [informalsystems/modelator#236]
The CLI needs tests. We can use [mdx](https://github.com/realworldocaml/mdx), as the Apalache team did for their CLI: https://github.com/informalsystems/apalache/blob/main/test/tla/cli-integration-tests.md. Probably it would be a good idea to have multiple mdx files, instead of just one large file for the whole CLI. One file for each command, for instance.

**Comment by ivan-gavran** [comment]
This turned out to be a good idea. Closing this issue as we are using `mdx` regularly now.
