### ISSUE TITLE
[Suggestion] Allow to download unknown Apalache versions

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#244]
Currently, when in the context of #242 I do `modelator apalache get 0.28.0`, the following is printed:

```
Downloading Apalache version 0.28.0
ERROR: SHA Checksum is missing. Add it manually to `const_values.APALACHE_SHA_CHECKSUMS`
```

This is not very helpful for the end user: they can't modify built-in Modelator constants. 
I suggest we do the following, if a user requests to download an unknown Apalache version:
- if it can be found, download it
- compute its SHA256; if it is unknown, add the checksum to our database, and warn the user that this file has been added with this checksum.

That way a user will be able to use new Apalache versions if they want to; security-conscious users will be also able to verify, if they want, that the downloaded version is the intended one.

For the latter step, there is actually no easy way available, as SHA256 checksums are not provided anywhere on the Apalache releases. We could talk with the Apalache team: it might make sense to sign the releases. (publishing SHA256 on a website is also not an adequate level of protection anyway, see e.g. [this blogpost](https://micahflee.com/2016/02/backdoored-linux-mint-and-the-perils-of-checksums/)).

**Comment by rnbguy** [comment]
Apalache releases started offering checksums via informalsystems/apalache#1999.

I pushed a PR that tries to read checksums for unknown versions. If the checksum is not present (for older versions of Apalache), CLI simply throws the current error. Otherwise, it checks the real checksum against the checksum from release artifacts.
