### ISSUE TITLE
Change default trace dir to traces/<timestamp>

### ISSUE THREAD

**Issue by ivan-gavran** [informalsystems/modelator#252]
At the moment, when generating traces files, we add to their name a timestamp ([here](https://github.com/informalsystems/modelator/blob/0459768b227a830b4353d1684bad626c431cbf97/modelator/utils/apalache_helpers.py#L32)).

This creates problems because we do not know what will be the name of the traces file (the problems arise in presentation: tutorials, examples..., but also in users' experimentation, when they are iteratively trying generate traces and run tests on them) .
I am assuming that the timestamp was introduced to avoid overwriting traces file by subsequent runs of traces generation. 
However, this is partially taken care of by requiring a parameter for traces folder.

Thus, I propose to remove the timestamp. (Sequence numbers come from the Apalache already).

Alternatively, we could generate both (timestamped files for permanence, non-timestamped one for easier referring and easier experimentation by users).

What do you think, am I overlooking some use of the timestamp? @hvanz @rnbguy

**Comment by hvanz** [comment]
The trace directory is optional and, if it's not changed on every run, the traces will be generated in the same dir. Are Apalache sequence numbers enough to not overwrite old trace files?

**Comment by ivan-gavran** [comment]
Sequence numbers are not enough. But having both versions (timestamped & non-timestamped) would be enough.

On the second note: trace directory is optional, but if not provided (and also, config file not provided) it will be set to `None` so no traces will be generated (This surprised me actually, so it might be another thing to reconsider: [here](https://github.com/informalsystems/modelator/blob/0459768b227a830b4353d1684bad626c431cbf97/modelator/cli/model_config_file.py#L37))

**Comment by hvanz** [comment]
> On the second note: trace directory is optional, but if not provided (and also, config file not provided) it will be set to None so no traces will be generated (This surprised me actually, so it might be another thing to reconsider: [here](https://github.com/informalsystems/modelator/blob/0459768b227a830b4353d1684bad626c431cbf97/modelator/cli/model_config_file.py#L37))

Good point. This is addressed in the PR #249.

**Comment by ivan-gavran** [comment]
An idea from the sync by @hvanz : a nice solution might be to have as a default folder `traces/<timestamp>/`. That way, when the user consciously gives a folder name, there will be no mess with timestamps, while at the same time avoiding unintended overwriting of existing traces
