### ISSUE TITLE
Rename "examples" when sampling

### ISSUE THREAD

**Issue by hvanz** [informalsystems/modelator#277]
Currently the `modelator sample` command is like this: `modelator sample --model-path model/Test3.tla --examples ThreeSteps --max_error=3`.

@andrey-kuprianov's proposal: 

> I think we need to change it to `modelator sample --model-path model/Test3.tla --tests ThreeSteps --max-trace=3` , i.e. rename `--examples` to `--tests`:  examples don’t make much sense for us; it was a mistake to introduce this terminology in the first place.

**Comment by hvanz** [comment]
I think the name `tests` conflicts with other terminology in the current design. For example, this is in the [readme file](https://github.com/informalsystems/modelator/blob/cd3653e1e7f35675c5ce2d0c78775e1515863d7d/Modelator.md#L80):

> Having a model in place, what can you do with it? We identify three main possibilities: exploration of examples (sampling), verification (invariant checking), and testing (generation and execution of tests).

**Comment by andrey-kuprianov** [comment]
But that’s the point… I think introducing examples and tests as separate concepts in the above readme was an error from my side:
they describe the same: the desired trace shape (a positive example, not a counterexample)
they need to be treated the same: negated into the invariant, and then taking counterexample trace
According to the [Duck test](https://en.wikipedia.org/wiki/Duck_test), they are the same animal;) And for simplicity, I believe, we should call them just tests
