### ISSUE TITLE
modelator User Manual

### ISSUE THREAD

**Issue by niuzhi** [informalsystems/modelator#287]
Hello, I have been using TLA+ before, and I found that modelator is a good test method, but when I started to use modelator, I found that I could not find the relevant manual for modelator. Excuse me, is there a manual for modelator in the community? for me to learn and use

**Comment by rnbguy** [comment]
Hey, sorry for the late reply. Unfortunately, we don't have anything for the modelator particularly.

But you can follow the sibling project Atomkraft's tutorial [here](https://github.com/informalsystems/atomkraft/blob/dev/examples/cosmos-sdk/transfer/transfer.md). The idea stays the same.

I will try to cook up a similar but modelator-specific general example.

**Comment by rnbguy** [comment]
@niuzhi I put together a simple example here https://github.com/informalsystems/modelator/tree/rano/tutorial/examples/hanoi

I will keep improving it. Meanwhile, please let us know if something is unclear.

**Comment by niuzhi** [comment]
@rnbguy  sorry for the late reply，Thank you for the case you provided, I will study it as soon as possible

**Comment by niuzhi** [comment]
@rnbguy 
When I run the following command, I find that there is no options --tests

modelator sample --model-path model/hanoi.tla --tests Test --traces-dir traces

![image](https://user-images.githubusercontent.com/33443724/203453299-b7c39734-eb72-480d-b4cd-2d289f822f16.png)

**Comment by rnbguy** [comment]
@niuzhi probably you're using an older version. Run `pip install -U modelator` to update it.

Modelator is still at earlier stages, so there are API breakages among newer versions :slightly_smiling_face:

**Comment by niuzhi** [comment]
@rnbguy thanks。
There is one more question I need to ask you, please take the time to help answer it, thank you very much.
question:
I learned from https://mbt.informal.systems/docs/modelator.html that modelator supports TLC, so I would like to ask how to convert the traces generated by tlc into ITF.json, which will be called by subsequent pytest test programs
