### ISSUE TITLE
Add timeout option for test execution time.

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#31]
Similar to Tendermint-rs Lightclient tests, we need to add the possibility for the user to specify a timeout on how long the test execution should take at most.

**Comment by rnbguy** [comment]
I assume we are talking about the use cases like this 
https://github.com/informalsystems/modelator/blob/b45faeb866a01e7ff714bb4f32904d8389b69f2b/modelator/src/module/tlc/mod.rs#L56-L58

It may be bit of a canon, but can we introduce `tokio-rs` and use `select` API?
