### ISSUE TITLE
Make modelator crate publishable

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#41]
We want to publish modelator crate in the next couple of days; as it turned out this is not possible after including JARs into the crate (see #21), as the crate size then exceeds the allowed limit of 10MB.

We need either to temporarily revert the changes done in #21, or think about some other solution avoid packaging the JARs into the crate.

**Comment by romac** [comment]
Perhaps we can ask the crates.io team to raise the limit for `modelator`? See `https://github.com/rust-lang/crates.io/issues/195#issuecomment-142451847`

Their email can be found in the footer of the crates.io homepage, under `Send us an email`.

**Comment by romac** [comment]
But at the end of the day, downloading the JARs is fine too.

**Comment by andrey-kuprianov** [comment]
I think the way Vitor has implemented this in #42 is actually good. We may consider applying for the extended limit, but probably later -- we will see whether the current mechanism poses any problems.
