### ISSUE TITLE
Non-deterministic test failures & behaviour

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#43]
Our tests behave non-deterministically:
 - from time to time some tests fail: I get the failures for `tester::tests::test` as well as for `apalache`. The weird thing is that most times they succeed, but sometimes just fail;
 - the temporary files created in `tests/integration/tla` are not always deleted. This could be fixed via #33.
 
Most frequently this is triggered when something needs to be recompiled, but not necessarily so. 

We need to fix that -- a testing tool should have it's own testing done right;)

**Comment by andrey-kuprianov** [comment]
Related to #33 : model checker files are not cleaned up, therefore the tests can fail in different ways depending on the order of their execution. 

A concrete example:

- in [run 1](https://github.com/informalsystems/modelator/runs/2436853472) the test fails with a weird result, that has nothing to do with the test itself.
- in [run 2](https://github.com/informalsystems/modelator/runs/2437714803) the test fails saying that no Apalache counterexample found.

The difference between the two is this [test reordering](https://github.com/informalsystems/modelator/commit/058ee96940d4ac8ee2d1b0a9c15fc8f5d64dbce9#diff-43127f1f26103ddd943b708e6325112af63da89bec7a7a012e354323f3326cfbL124). What fails:
 - For `numbers_a_max_b_max_test` Apalache fails to find a couterexample, because by default it explores only up to the length of 10, and this test requires a longer sequence.
 - If this test is at the end, as in run 1, **the counterexample from the previous test is silently reused**. This is really bad.
 - If this test is in the beginning, the test fails, correctly saying that it can't find Apalache counterexample. 

The point is that the whole sequence of calls at all places needs to be examined and cleaned, and the interfaces clearly specified. Here are a few things:
 - #33 needs to be implemented, otherwise we will keep getting errors like above
 - The communication with the user needs to be improved. E.g. in the case when Apalache counterexample can't be found, it needs to be recommended to increase the length of explored counterexamples. Plus there should be either such configuration parameter, or it should be increased automatically
 - There are some places where we don't know what and when exactly happens. E.g., I was surprised to see that for tests the **generated files are deleted twice** -- see  058ee96.

**Comment by andrey-kuprianov** [comment]
Seems to be fixed via #33 -- the tests pass for me now multiple times in a row.

Having said that, we still need to carefully examine everything, and have a clear understanding what and how we test.

Closing for now.

**Comment by andrey-kuprianov** [comment]
The tests still fail non-deterministically -- see e.g. this [run](https://github.com/informalsystems/modelator/runs/3159325596?check_suite_focus=true).

Reopening.

**Comment by andrey-kuprianov** [comment]
As it seems to me, the handling of TLC output is not implemented correctly, which was the reason for non-deterministic test failures. E.g. [this commit](https://github.com/informalsystems/modelator/pull/44/commits/78e3e2927f26f227d5afe6cc669a85e539395337) fixed non-determinism for PR #44. 

[This code fragment](https://github.com/informalsystems/modelator/blob/b5148c6c325b12923b0de0622e198101e89861ff/modelator/src/module/tlc/mod.rs#L60-L132) looks suspicious to me: it may be that sometimes the information in the TLC output is sufficient to extract the trace, and sometimes not. I think the trace should be extracted from `MC.out`, and not from the tool output.

**Comment by rnbguy** [comment]
@andrey-kuprianov is there any update with this issue? Except I enable `Cache`, I didn't see any non-det behaviors lately.

**Comment by andrey-kuprianov** [comment]
@rnbguy It might be that non-determinism was caused by the storage of model-checker output in the current directory. With everything now in tempdirs, and also with your changes to handling TLC, this might get resolved. If you think this is resolved, just close the issue. We will see:)

But in general we will need to streamline the architecture and understand/eliminate completely all sources of non-determinism. I think we are gradually moving in that direction.

**Comment by danwt** [comment]
Closed as resolved. Please reopen if necessary.
