### ISSUE TITLE
Cache doesn't work correctly

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#46]
Caching of MC results doesn't work as expected. I have a [failing run in CI](https://github.com/informalsystems/modelator/runs/2466823207), but the tests run fun on my laptop. After removing `.modelator/cache` dir, I get the same test failure. Upon the next test run, all tests pass again.

Related to #43

**Comment by andrey-kuprianov** [comment]
The cache will be disabled for now. It need to be refactored to integrate well with temporary directories (see #33, #47).

**Comment by rnbguy** [comment]
Since we have `Artifact` struct, can we implement the cache in-memory now? Or do we want the cache to persist between runs?

**Comment by andrey-kuprianov** [comment]
We want the cache to persist, actually.

**Comment by danwt** [comment]
Closed as outdated. Please reopen if this is a mistake. (Cache is completely disabled and our new product vision will have a different kind of cache altogether)
