### ISSUE TITLE
Possible refactoring and API improvements

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#50]
Pulling in here the suggestions from the reviews of PR #44, which should not necessarily addressed right away, but are rather about long-term improvements:

- If you think it's useful, you can always add a run_with_default method which requires the Default bound and uses the default value of the system. https://github.com/informalsystems/modelator/pull/44#issuecomment-827512769
- remove redundant `Default` impls and `::new()` fns. Instead derive `Default`: https://github.com/informalsystems/modelator/pull/44#discussion_r677005495
- make run_tla_steps and run_tla_events convenient struct methods. The function bodies are very small and very direct anyway: https://github.com/informalsystems/modelator/pull/44#discussion_r677010105
- use the power of `AsRef` or `Deref`: https://github.com/informalsystems/modelator/pull/44#discussion_r677011567
- Why `Action` is generic type and `Outcome` is associated type? `Action` does not have trait bounds. We can make `Action` as an associated type too? : https://github.com/informalsystems/modelator/pull/44#discussion_r677013516
- I saw some 'static and DeserializeOwned bounds here and there. Are these lifetimes sanitized? If it is not done yet, I can take a look later. It would remove unnecessary lifetime bounds. https://github.com/informalsystems/modelator/pull/44#issuecomment-887110229

**Comment by rnbguy** [comment]
Would it be a good idea to parallelize some parts of the code as well?

Something like [this](https://github.com/informalsystems/modelator/compare/06ed539...8616150).
