### ISSUE TITLE
Confusing "No test trace found" error state

### ISSUE THREAD

**Issue by jtremback** [informalsystems/modelator#52]
The error state

```
Err(
    NoTestTraceFound(
        "mc.log",
    ),
)
```

Is produced by several different error conditions, making debugging hard and confusing. For example:

- It was produced when I forgot an invariant in `IBCTests.cfg`. In TLC this yielded the much more informative error message `The invariant Neg specified in the configuration file is not defined in the specification.`
- It is produced when any of the `*Test` operators in a TLA+ file does not yield an error trace when negated. A single one of the `*Test` operators in a TLA+ spec not yielding an error trace when negated will result in this error being produced with no indication of which one caused the problem. To find and fix it involves a slow process of trying to negate each `*Test` operator and seeing if a trace is produced.

**Comment by andrey-kuprianov** [comment]
Thank you for reporting this, @jtremback! We will fix that.

**Comment by rnbguy** [comment]
Note. `output::parse` should parse the whole output for possible error hints.

https://github.com/informalsystems/modelator/blob/b45faeb866a01e7ff714bb4f32904d8389b69f2b/modelator/src/module/tlc/output.rs#L8-L15

**Comment by rnbguy** [comment]
@jtremback I added prelim changes to detect error messages from TLC. Feedbacks are welcome on this branch.

**Comment by jtremback** [comment]
Oh cool! I'll take a look

**Comment by andrey-kuprianov** [comment]
Closed via #74
