### ISSUE TITLE
Refactor error handling

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#53]
We do indeed need to refactor the error reporting, as highlighted by #52:
 
- [x] make the errors as specific as possible, not bundle them together into a huge super-error (e.g. report per each test assertion, not per file with a bunch of assertions)
- [x] propagate a reasonable amount of information from the model checkers, to help the user understanding the errors

**Comment by rnbguy** [comment]
By looking at the error traces, I propose that I create multiple error enums.
- TLC
- Apalache
- TLA-parser
- MBT-core
- etc.

This way, we can track each case. Also, if we split the current crate into multiple crates, we can just take the Error enums for each module.

PS. I will also start looking at TLC and Apalache as different modules for a future-proof refactor.

**Comment by andrey-kuprianov** [comment]
Closed via #68 and #74.
