### ISSUE TITLE
Allow to select model checker version

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#54]
Currently [here](https://github.com/informalsystems/modelator/blob/06ed539eba8c16d41a80e70c271c5799d28c5e7a/modelator/src/options.rs#L82-L91) the model checker choice is limited to unversioned TLC or Apalache, which defaults to already pretty outdated versions of both. We need to change this scheme as follows:

 - leave those options, but now they should refer to the latest version of the model checkers bundled with the corresponding modelator release
 - add versioned options, e.g. `TlcVersion(String)`, and `ApalacheVersion(String)`, that would attempt to download a specific version of model checkers. This will allow both to deterministically fix the MC versions for some tests, as well as to experiment with the newer versions of model checkers.

**Comment by andrey-kuprianov** [comment]
postponing to v.0.4; integration of recent versions of Apalache will require more work (see #81)

**Comment by shonfeder** [comment]
We've discussed setting up integration tests to check the head of modelator against the head of apalche, so we'll get advanced warning of any breakage or needs to patch one way or the other. Andrey noted that this is a pre-requisite for such tests.

**Comment by danwt** [comment]
This should be implemented as part of mbt-python/mbt-core.
