### ISSUE TITLE
Running binary with only the argument `tla` causes panic instead of giving warning to user.

### ISSUE THREAD

**Issue by danwt** [informalsystems/modelator#55]
Bug:

Running binary `./modelator tla` panics. 

Expected:

`./modelator --help` gives

```
SUBCOMMANDS:
    apalache    Generate TLA+ traces using Apalache
    tla         Generate TLA+ test cases and parse TLA+ traces
    tlc         Generate TLA+ traces using TLC
```

so it is expected that a user will try to pass only `tla` arg.

Log:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', modelator/src/cli/mod.rs:29:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Additional info:

Tested on _release_ in versions 0.2.0 and [(06ed539eb) latest](https://github.com/informalsystems/modelator/commit/06ed539eba8c16d41a80e70c271c5799d28c5e7a)

**Comment by andrey-kuprianov** [comment]
Fixed by https://github.com/informalsystems/modelator/commit/e4a94f9c9b448fea305ff1f33a65ea5463e3bbe3; closing
