### ISSUE TITLE
Generic Jsonnet executor

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/modelator#8]
We are going to have a large number of MBT-core modules implemented as small Jsonnet programs. We need to implement the way to execute arbitrary Jsonnet program that satisfies the requirements outlined in https://github.com/informalsystems/modelator/issues/2#issuecomment-775959504 as an MBT-core module.

Modelator will then come with a prepackaged set of Jsonnet-based modules, that the end user will be able to extend at will.

**Comment by danwt** [comment]
Closed as outdated. Please reopen if this is a mistake.
