### ISSUE TITLE
System in run_tla_steps has trait bound of debug

### ISSUE THREAD

**Issue by jtremback** [informalsystems/modelator#84]
Is this really necessary? System, at least how I'm using it, tends to be a struct with a grab bag of state used to run the test. For example, a GRPC library which is statefully initialized with a url. The library I'm using does not implement Debug, so I cannot derive Debug on System, and need to implement it manually.

**Comment by rnbguy** [comment]
Interesting situation. Meanwhile, you can [`derivative`](https://github.com/mcarton/rust-derivative#what-it-does) to go around this easily.

```
#[derive(Derivative)]
#[derivative(Debug)]
struct Foo {
    foo: u8,
    #[derivative(Debug="ignore")]
    bar: u8,
}

// Prints `Foo { foo: 42 }`
println!("{:?}", Foo { foo: 42, bar: 1 });
```

**Comment by rnbguy** [comment]
@jtremback I think you were talking about the `Contact` struct. For unit-like structs, the syntax is similar.

```
#[derive(Derivative)]
#[derivative(Debug)]
struct Foo(u8, #[derivative(Debug = "ignore")] u8);

// Prints `Foo(42)`
println!("{:?}", Foo(42, 1));
```

**Comment by jtremback** [comment]
I was just using the wrapper type to implement Debug on myself. I should be able to use derivative to implement Debug on System while ignoring the GRPC library
