### ISSUE TITLE
Might be nice to get more details about parse failures

### ISSUE THREAD

**Issue by jtremback** [informalsystems/modelator#91]
I don't know if there's an easy solution to this, but it's often hard to figure out what went wrong when there is an issue parsing traces. You get an error like this:

```
    Err(
        Modelator(
            JsonParseError(
                "invalid value: map, expected map with a single key",
            ),
        ),
    ),
```

This doesn't tell you where the problem is. Not sure if there's a way to improve on this.

**Comment by rnbguy** [comment]
Can I see the JSON trace? If it is a JSON trace produced by the moderator, it should not raise this `Error`.

**Comment by jtremback** [comment]
Yes, I'll try to recreate it and get you the trace. The specific scenario was that I had a TLA+ record which was essentially both an externally tagged and an internally tagged enum:

```
    (* @type: [
        actionType: Str,
        SendToEthereum: [ validator: Int, sendAmount: Int ],
        Erc20DeployedEvent: [ eventNonce: Int ],
        Init: [ flag: Int ]
    ]*)
```

Serde only accepts externally tagged enums as long as they are the only thing in the object representing the enum. So, this would have worked:

```
    (* @type: [
        SendToEthereum: [ validator: Int, sendAmount: Int ],
        Erc20DeployedEvent: [ eventNonce: Int ],
        Init: [ flag: Int ]
    ]*)
```

Basically, the struct definitions I was giving modelator did not match up with what the TLA+ was producing.

**Comment by ivan-gavran** [comment]
Closing, since the parser and the whole tool architecture got completely changed in the meantime.
